.TH IRTT 1 "February 3, 2018" "IRTT 0.9" "Isochronous Round\-Trip Time Manual"
.SH NAME
.PP
irtt \- Isochronous Round\-Trip Time
.SH DESCRIPTION
.PP
\fB\fCfoo\fR frobnicates the bar library by tweaking internal symbol tables. By
default it parses all baz segments and rearranges them in reverse order by
time for the 
.BR xyzzy (1) 
linker to find them. The symdef entry is then compressed
using the WBG (Whiz\-Bang\-Gizmo) algorithm. All files are processed in the
order specified.
.TS
allbox;
cb cb
l l
l l
.
First Header	Second Header
Content Cell	Content Cell
Content Cell that's wider	Content Cell
.TE
.SH BUGS
.PP
The command name should have been chosen more carefully to reflect its
purpose.
.SH AUTHOR
.PP
Pete Heist \[la]pete@eventide.io\[ra]
.SH SEE ALSO
.PP
.BR irtt-client (1), 
.BR irtt-server (1)

IRTT GitHub repository \[la]https://github.com/peteheist/irtt/\[ra]
