// Code generated by "stringer -type=ErrorCode"; DO NOT EDIT.

package irtt

import "fmt"

const _ErrorCode_name = "InvalidWinAvgWindowInvalidExpAvgAlphaDSCPErrorDFErrorTTLErrorShortWriteExpectedReplyFlagUnexpectedReplyFlagShortReplyStampAtMismatchClockMismatchUnexpectedSequenceNumberInvalidDFStringFieldsLengthTooLargeFieldsCapacityTooLargeInvalidStampAtStringInvalidStampAtIntInvalidAllowStampStringInvalidClockStringInvalidClockIntInvalidSleepFactorIntervalNotPermittedInvalidWaitStringInvalidWaitFactorInvalidWaitDurationNoSuchAveragerNoSuchFillerNoSuchTimerNoSuchWaiterBadMagicNoHMACBadHMACUnexpectedHMACNonexclusiveMidpointTStampInconsistentClocksListenerPanicDFNotSupportedIntervalNonPositiveDurationNonPositiveConnTokenZeroConnClosedInvalidFlagBitsSetServerClosedShortParamBufferParamOverflowUnknownParamNoSuitableAddressFoundOpenTimeoutInvalidServerRestrictionInvalidParamValueParamsChangedInvalidReceivedStatsIntInvalidReceivedStatsStringOpenTimeoutTooShort"

var _ErrorCode_index = [...]uint16{0, 19, 37, 46, 53, 61, 71, 88, 107, 117, 132, 145, 169, 184, 204, 226, 246, 263, 286, 304, 319, 337, 357, 374, 391, 410, 424, 436, 447, 459, 467, 473, 480, 494, 520, 538, 551, 565, 584, 603, 616, 626, 644, 656, 672, 685, 697, 719, 730, 754, 771, 784, 807, 833, 852}

func (i ErrorCode) String() string {
	if i < 0 || i >= ErrorCode(len(_ErrorCode_index)-1) {
		return fmt.Sprintf("ErrorCode(%d)", i)
	}
	return _ErrorCode_name[_ErrorCode_index[i]:_ErrorCode_index[i+1]]
}
