// Code generated by "stringer -type=ErrorCode"; DO NOT EDIT.

package irtt

import "fmt"

const _ErrorCode_name = "InvalidWinAvgWindowInvalidExpAvgAlphaDSCPErrorDFErrorTTLErrorShortWriteExpectedReplyFlagUnexpectedReplyFlagShortReplyStampAtMismatchClockMismatchUnexpectedSequenceNumberInvalidDFStringFieldsLengthTooLargeFieldsCapacityTooLargeInvalidStampAtStringInvalidAllowStampStringInvalidClockStringInvalidSleepFactorIntervalNotPermittedInvalidWaitStringInvalidWaitFactorInvalidWaitDurationNoSuchAveragerNoSuchFillerNoSuchTimerNoSuchWaiterBadMagicNoHMACBadHMACUnexpectedHMACNonexclusiveMidpointTStampInconsistentClocksListenerPanicDFNotSupportedIntervalNonPositiveDurationNonPositiveOpenCloseBothSetConnTokenZeroConnClosedInvalidFlagBitsSetServerClosedShortParamBufferParamOverflowUnknownParamNoSuitableAddressFoundOpenTimeoutInvalidServerRestriction"

var _ErrorCode_index = [...]uint16{0, 19, 37, 46, 53, 61, 71, 88, 107, 117, 132, 145, 169, 184, 204, 226, 246, 269, 287, 305, 325, 342, 359, 378, 392, 404, 415, 427, 435, 441, 448, 462, 488, 506, 519, 533, 552, 571, 587, 600, 610, 628, 640, 656, 669, 681, 703, 714, 738}

func (i ErrorCode) String() string {
	if i < 0 || i >= ErrorCode(len(_ErrorCode_index)-1) {
		return fmt.Sprintf("ErrorCode(%d)", i)
	}
	return _ErrorCode_name[_ErrorCode_index[i]:_ErrorCode_index[i+1]]
}
