// Code generated by "stringer -type=EventCode"; DO NOT EDIT.

package irtt

import "fmt"

const _EventCode_name = "MultipleAddressesListenerStartListenerStopListenerErrorDropBadMagicDropNoHMACDropBadHMACDropUnexpectedHMACDropNonexclusiveMidpointStampDropInconsistentClocksDropPacketErrorDropExpectedReplyDropUnexpectedReplyDropUnexpectedOpenFlagDropSmallPacketDropInvalidFlagBitsSetDropInvalidConnTokenDropAddressMismatchDropUnparseableParamsDropShortIntervalSockoptDSCPFailSockoptDSCPAbortSockoptDFFailSockoptDFAbortConnectingConnectedWaitForPacketsNewConnOpenCloseCloseConnNoDSCPSupportServerRestrictionDurationLimitExceededNoTest"

var _EventCode_map = map[EventCode]string{
	1:          _EventCode_name[0:17],
	2:          _EventCode_name[17:30],
	4:          _EventCode_name[30:42],
	8:          _EventCode_name[42:55],
	16:         _EventCode_name[55:67],
	32:         _EventCode_name[67:77],
	64:         _EventCode_name[77:88],
	128:        _EventCode_name[88:106],
	256:        _EventCode_name[106:135],
	512:        _EventCode_name[135:157],
	1024:       _EventCode_name[157:172],
	2048:       _EventCode_name[172:189],
	4096:       _EventCode_name[189:208],
	8192:       _EventCode_name[208:230],
	16384:      _EventCode_name[230:245],
	32768:      _EventCode_name[245:267],
	65536:      _EventCode_name[267:287],
	131072:     _EventCode_name[287:306],
	262144:     _EventCode_name[306:327],
	524288:     _EventCode_name[327:344],
	1048576:    _EventCode_name[344:359],
	2097152:    _EventCode_name[359:375],
	4194304:    _EventCode_name[375:388],
	8388608:    _EventCode_name[388:402],
	16777216:   _EventCode_name[402:412],
	33554432:   _EventCode_name[412:421],
	67108864:   _EventCode_name[421:435],
	134217728:  _EventCode_name[435:442],
	268435456:  _EventCode_name[442:451],
	536870912:  _EventCode_name[451:460],
	1073741824: _EventCode_name[460:473],
	2147483648: _EventCode_name[473:490],
	4294967296: _EventCode_name[490:511],
	8589934592: _EventCode_name[511:517],
}

func (i EventCode) String() string {
	if str, ok := _EventCode_map[i]; ok {
		return str
	}
	return fmt.Sprintf("EventCode(%d)", i)
}
