// Code generated by "stringer -type=EventCode"; DO NOT EDIT.

package irtt

import "fmt"

const _EventCode_name = "ListenerStartListenerStopListenerErrorDropBadMagicDropNoHMACDropBadHMACDropUnexpectedHMACDropNonexclusiveMidpointStampDropInconsistentClocksDropPacketErrorDropExpectedReplyDropUnexpectedReplyDropUnexpectedOpenFlagDropSmallPacketDropOpenCloseBothSetDropInvalidFlagBitsSetDropInvalidConnTokenDropAddressMismatchDropUnparseableParamsDropShortIntervalSockoptDSCPFailSockoptDSCPAbortSockoptDFFailSockoptDFAbortConnectingConnectedWaitForPacketsNewConnCloseConnNoDSCPSupportServerRestrictionDurationLimitExceeded"

var _EventCode_map = map[EventCode]string{
	1:          _EventCode_name[0:13],
	2:          _EventCode_name[13:25],
	4:          _EventCode_name[25:38],
	8:          _EventCode_name[38:50],
	16:         _EventCode_name[50:60],
	32:         _EventCode_name[60:71],
	64:         _EventCode_name[71:89],
	128:        _EventCode_name[89:118],
	256:        _EventCode_name[118:140],
	512:        _EventCode_name[140:155],
	1024:       _EventCode_name[155:172],
	2048:       _EventCode_name[172:191],
	4096:       _EventCode_name[191:213],
	8192:       _EventCode_name[213:228],
	16384:      _EventCode_name[228:248],
	32768:      _EventCode_name[248:270],
	65536:      _EventCode_name[270:290],
	131072:     _EventCode_name[290:309],
	262144:     _EventCode_name[309:330],
	524288:     _EventCode_name[330:347],
	1048576:    _EventCode_name[347:362],
	2097152:    _EventCode_name[362:378],
	4194304:    _EventCode_name[378:391],
	8388608:    _EventCode_name[391:405],
	16777216:   _EventCode_name[405:415],
	33554432:   _EventCode_name[415:424],
	67108864:   _EventCode_name[424:438],
	134217728:  _EventCode_name[438:445],
	268435456:  _EventCode_name[445:454],
	536870912:  _EventCode_name[454:467],
	1073741824: _EventCode_name[467:484],
	2147483648: _EventCode_name[484:505],
}

func (i EventCode) String() string {
	if str, ok := _EventCode_map[i]; ok {
		return str
	}
	return fmt.Sprintf("EventCode(%d)", i)
}
