// Code generated by "stringer -type=EventCode"; DO NOT EDIT.

package irtt

import "fmt"

const _EventCode_name = "MultipleAddressesListenerStartListenerStopListenerErrorDropBadMagicDropNoHMACDropBadHMACDropUnexpectedHMACDropNonexclusiveMidpointStampDropInconsistentClocksDropPacketErrorDropExpectedReplyDropUnexpectedReplyDropUnexpectedOpenFlagDropSmallPacketDropOpenCloseBothSetDropInvalidFlagBitsSetDropInvalidConnTokenDropAddressMismatchDropUnparseableParamsDropShortIntervalSockoptDSCPFailSockoptDSCPAbortSockoptDFFailSockoptDFAbortConnectingConnectedWaitForPacketsNewConnCloseConnNoDSCPSupportServerRestrictionDurationLimitExceeded"

var _EventCode_map = map[EventCode]string{
	1:          _EventCode_name[0:17],
	2:          _EventCode_name[17:30],
	4:          _EventCode_name[30:42],
	8:          _EventCode_name[42:55],
	16:         _EventCode_name[55:67],
	32:         _EventCode_name[67:77],
	64:         _EventCode_name[77:88],
	128:        _EventCode_name[88:106],
	256:        _EventCode_name[106:135],
	512:        _EventCode_name[135:157],
	1024:       _EventCode_name[157:172],
	2048:       _EventCode_name[172:189],
	4096:       _EventCode_name[189:208],
	8192:       _EventCode_name[208:230],
	16384:      _EventCode_name[230:245],
	32768:      _EventCode_name[245:265],
	65536:      _EventCode_name[265:287],
	131072:     _EventCode_name[287:307],
	262144:     _EventCode_name[307:326],
	524288:     _EventCode_name[326:347],
	1048576:    _EventCode_name[347:364],
	2097152:    _EventCode_name[364:379],
	4194304:    _EventCode_name[379:395],
	8388608:    _EventCode_name[395:408],
	16777216:   _EventCode_name[408:422],
	33554432:   _EventCode_name[422:432],
	67108864:   _EventCode_name[432:441],
	134217728:  _EventCode_name[441:455],
	268435456:  _EventCode_name[455:462],
	536870912:  _EventCode_name[462:471],
	1073741824: _EventCode_name[471:484],
	2147483648: _EventCode_name[484:501],
	4294967296: _EventCode_name[501:522],
}

func (i EventCode) String() string {
	if str, ok := _EventCode_map[i]; ok {
		return str
	}
	return fmt.Sprintf("EventCode(%d)", i)
}
